const langs = [
    {
        heroMain: "Indian manufactured products to the world.",
        heroSub: "Businesses are evolving - causing tectonic shifts in the economic landscape. Explore new possibilities for B2B businesses.",
        joinAsMerchant: "Join as Merchant",
        getNotified: "Get Notified",
        joinAsB2BMerchant: "Join as a B2B Merchant",
        b2bMerchHero1: "Join a revolutionary marketplace that showcases your products to the entire world!",
        b2bMerchHero2: "Get more orders and grow your customer base with new business models like dropshipping. Export private labeled products and expand your global presence.",
        name: "Name",
        companyName: "Company Name",
        address1: "Address Line 1",
        address2: "Address Line 2",
        category: "Category",
        city: "City",
        state: "State",
        phone: "Phone",
        email: "Email",
        submit: "Submit",
        loading: "Loading...",
        somethingWentWrong: "Something went wrong :(",
        submissionSuccess: "Submission Successful!",
        agreeJoinPrivacyPolicy: "*By joining you agree to our terms and conditions & privacy policy",
        b2bConsumer: "B2B Consumer?",
        b2bConsumerHero: "If you are a B2B consumer, be the first ones to know when our marketplace goes live!",
        notifyMe: "Notify Me",
        subscribed: "Subscribed!",
        agreeSubPrivacyPolicy: "*By subscribing you agree to our terms and conditions &amp; privacy policy",
    },
    {
        heroMain: "दुनिया के लिए भारतीय निर्मित उत्पाद।",
        heroSub: "व्यवसाय विकसित हो रहे हैं - जिससे आर्थिक परिदृश्य में विवर्तनिक बदलाव हो रहे हैं। B2B व्यवसायों के लिए नई संभावनाओं का पता लगाएं",
        joinAsMerchant: "व्यापारी के रूप में शामिल हों",
        getNotified: "सूचनाएं प्राप्त करें",
        joinAsB2BMerchant: "बी 2 बी  व्यापारी के रूप में शामिल हों",
        b2bMerchHero1: "एक क्रांतिकारी बाजार में शामिल हों जो आपके उत्पादों को पूरी दुनिया में प्रदर्शित करता है! ",
        b2bMerchHero2: "अधिक ऑर्डर प्राप्त करें और अपने बिजनेस बेस को नए बिजनेस मॉडल जैसे ड्रापशीपिंग के साथ बढ़ाएं। निजी लेबल वाले उत्पादों का निर्यात करें और अपनी वैश्विक उपस्थिति का विस्तार करें।",
        name: "नाम",
        companyName: "कंपनी का नाम",
        address1: "पता 1",
        address2: "पता 2",
        category: "वर्ग",
        city: "शहर",
        state: "राज्य",
        phone: "फ़ोन",
        email: "ईमेल",
        submit: "प्रस्तुत",
        loading: "लोड हो रहा है..",
        somethingWentWrong: "कुछ गलत हो गया :(",
        submissionSuccess: "सबमिशन सफल!",
        agreeJoinPrivacyPolicy: "*शामिल होने से आप हमारे नियमों और शर्तों और गोपनीयता नीति से सहमत होते हैं",
        b2bConsumer: "B2B उपभोक्ता?",
        b2bConsumerHero: "यदि आप बी 2 बी उपभोक्ता हैं, तो सबसे पहले जानिए की कि कब आपका बाजार सजीव होता है!",
        notifyMe: "सूचित करें",
        subscribed: "सदस्यता लिया!",
        agreeSubPrivacyPolicy: "*सदस्यता लेने से आप हमारे नियमों और शर्तों और गोपनीयता नीति से सहमत होते हैं",
    },
    {
        heroMain: "இந்தியர்கள் தயாரித்த ப ாருட்கள் உலகத்திற்கு",
        heroSub: "இந்த உலகம் மாறிக்ககாண்டே இருக்கிறது அடதட ால் வியா ாரமும் மாறிக்ககாண்டே இருக்கிறது. ி2 ி வணிகங்களின் புதிய திட்ேங்களளயும் சாத்தியங்களளயும் ககாண்டு யன்க றத் கதாேங்குங்கள்.",
        joinAsMerchant: "ஒரு விற் னையாளராக சேரவும்",
        getNotified: "அறிவிப்புகனளப் ப ற",
        joinAsB2BMerchant: "ஒரு விற் னையாளராக சேரவும்",
        b2bMerchHero1: "இந்திய உற் த்தியாளர்கள் வழங்கும் லவளகயான விஷயங்களளக் காண் ிக்கும் ஒரு புரட்சிகர மார்க்ககட்டிங்கில் இளணய உங்களள அளழக்கிடறாம்.",
        b2bMerchHero2: "டிராப்ஷிப் ிங் (drop shipping ) ட ான்ற புதிய வணிக யுக்திகளுேன் கூடுதல் ஆர்ேர்களளப் க றுங்கள். அதுமட்டுமன்றி தனியார் ( உங்கள் ) க யரிேப் ட்ே தயாரிப்புகளள ஏற்றுமதி கசய்து உங்கள் வணிக சாம்ராஜ்யத்ளத விரிவாக்குங்கள் !",
        name: "பெயர்",
        companyName: "நிறுவனத்தின் பெயர்",
        address1: "முகவரி வரி 1",
        address2: "முகவரி வரி 2",
        category: "வகை",
        city: "நகரம்",
        state: "நிலை",
        phone: "தொலைபேசி",
        email: "மின்னஞ்சல்",
        submit: "சமர்ப்பிக்கவும்",
        loading: "ஏற்றுகிறது ...",
        somethingWentWrong: "ஏதோ தவறு நடைபெற்றிருக்கிறது :(",
        submissionSuccess: "சமர்ப்பிப்பு வெற்றிகரமாக!",
        agreeJoinPrivacyPolicy: "*சேருவதன் மூலம் எங்கள் விதிமுறைகள் மற்றும் நிபந்தனைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்",
        b2bConsumer: "நீங்கள் ி2 ி நுகர்சவாரா ?",
        b2bConsumerHero: "நீங்கள் ஒரு ி2 ி நுகர்டவார் என்றால், எங்கள் சந்ளத டநரளலக்கு வரும்ட ாது முதலில் கதரிந்து ககாள்ளுங்கள்!",
        notifyMe: "எனக்கு தெரியப்படுத்து",
        subscribed: "சந்தா!",
        agreeSubPrivacyPolicy: "*சந்தா செலுத்துவதன் மூலம் எங்கள் விதிமுறைகள் மற்றும் நிபந்தனைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்",
    }
]

export default langs